### PR TITLE
increase timeout in TestConnectionsClosedIfNotAccepted on CI

### LINKED ISSUE #84: flaky TestConnectionsClosedIfNotAccepted test
```
=== RUN   TestConnectionsClosedIfNotAccepted
    listener_test.go:124: connection closed earlier than expected. expected nothing on channel, got: <nil>
--- FAIL: TestConnectionsClosedIfNotAccepted (0.20s)

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #84.

### CODE REVIEW

File: listener_test.go [hunk 1]
```diff
@@ -91,9 +92,13 @@ func TestAcceptMultipleConns(t *testing.T) {
...
 
-	const timeout = 200 * time.Millisecond
+	var timeout = 100 * time.Millisecond
+	if os.Getenv("CI") != "" {
+		timeout = 500 * time.Millisecond
+	}
+	origAcceptTimeout := transport.AcceptTimeout
 	transport.AcceptTimeout = timeout
-	defer func() { transport.AcceptTimeout = 1 * time.Hour }()
+	defer func() { transport.AcceptTimeout = origAcceptTimeout }()
```
Comment (Stebalien) [inline listener_test.go:101]: nit: use `testing.Cleanup`

**Review by Stebalien — APPROVED** [review]

**Review by Stebalien — APPROVED** [review]
